set -g prefix ^S

# status
set -g status on
set -g status-interval 2
set -g status-style bg=#357302,fg=#FAFAFA

# windows
set -g window-status-format " #I:#W "

# Lado direito (info útil)
set -g status-right "#[fg=#f9e2af]#(whoami) #[fg=#89b4fa]%H:%M #[fg=#f38ba8]#(git branch 2>/dev/null | grep '*' | sed 's/* //')"

set -g base-index 1
set -g renumber-windows on
set -g detach-on-destroy off

#setw -g mode-keys vi
#bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
#set-option -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
set -g mouse on

set-option -g status-position bottom
